repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
        args: [--branch, main]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.5.6'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format

- repo: https://github.com/jazzband/pip-tools
  rev: 7.4.1
  hooks:
    - id: pip-compile
      name: Check requirements.txt up-to-date
      args: ["--resolver=backtracking", "--extra=all", "--output-file=requirements.txt"]
      files: ^(pyproject\.toml|requirements\.txt)$
