name: Build and Push Docker Image

on:
    workflow_call:
        inputs:
            package-base-version:
                description: Python Package version
                required: true
                type: string
            package-dev-version:
                description: The Dev Python Package version
                required: true
                type: string
        secrets:
            DOCKERHUB_USERNAME:
                required: true
            DOCKERHUB_TOKEN:
                required: true

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event_name == 'pull_request' && github.event.inputs.base_ref || github.ref }}
                fetch-depth: 0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            - name: Set Docker Tag
              id: set-tag
              run: |
                if [ "${{ github.ref }}" = "refs/heads/main" ]; then
                    echo "DOCKER_TAG=${{ inputs.package-base-version }}" >> $GITHUB_ENV
                else
                    echo "DOCKER_TAG=${{ inputs.package-dev-version }}" >> $GITHUB_ENV
                fi

            - name: Build and Push Docker Image
              run: |
                docker buildx build --platform linux/amd64,linux/arm64 \
                -t ${{ secrets.DOCKERHUB_USERNAME}}/cuda_ops:${{ env.DOCKER_TAG }} -f Dockerfile . --output type=docker

            # This step can be run only if we have a GPU runner
            # - name: Run tests inside Docker container
            #   run: |
            #     docker run ${{ secrets.DOCKERHUB_USERNAME}}/cuda_ops:${{ env.DOCKER_TAG }} bash -c "pytest -s /opt/cuda_ops/test/test.py"

            - name: Push Image
              run: |
                docker push ${{ secrets.DOCKERHUB_USERNAME}}/cuda_ops:${{ env.DOCKER_TAG }}
