name: Build and Push Docker Image

on:
    workflow_call:
        inputs:
            package-base-version:
                type: string
            package-dev-version:
                type: string
        secrets:
            DOCKERHUB_USERNAME:
                required: true
            DOCKERHUB_TOKEN:
                required: true

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: ${{ github.event_name == 'pull_request' && github.event.inputs.base_ref || github.ref }}
                fetch-depth: 0

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            - name: Build and Push Docker Image
              run: |
                docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/cuda_ops:${{ github.event.inputs.package-base-version }} -t ${{ secrets.DOCKERHUB_USERNAME }}/cuda_ops:${{ github.event.inputs.package-dev-version }} --push .
