name: Create release for Github

on:
    workflow_call:
        inputs:
            package-version:
                description: Python Package version
                required: true
                type: string
    push:
        tags:
            - 'v*'

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Create GH Release
              id: create-release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.TOKEN }}
              with:
                tag_name: ${{ inputs.package-version}}
                release_name: Release ${{ inputs.package-version }}
                body: |
                  Release for ${{ github.ref }}
                draft: false
                prerelease: false
