name: Create release for Github

on:
    workflow_call:
        inputs:
            package-base-version:
                description: Python Package version
                required: true
                type: string
        outputs:
            new-tag:
                description: The new tag for the release
                value: ${{ jobs.create-release.outputs.new_tag }}
        secrets:
            TOKEN:
                required: true
    push:
        tags:
            - 'v*'

jobs:
    create-release:
        runs-on: ubuntu-latest
        outputs:
            new_tag: ${{ steps.tag-version.outputs.new_tag}}

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Compute new version based on semantic
              id: tag-version
              uses: mathieudutour/github-tag-action@v6.1
              with:
                custom_tag: ${{ inputs.package-base-version }}
                github_token: ${{ secrets.TOKEN }}
            - name: Create GH Release
              uses: ncipollo/release-action@v1
              with:
                tag: ${{ steps.tag-version.outputs.new_tag }}
                name: ${{ steps.tag-version.outputs.new_tag }}
                body: ${{ steps.tag-version.outputs.changelog }}
