name: Nightly Build CI

on:
    schedule:
        - cron: '0 0 * * *'


permissions:
    id-token: write
    contents: write

jobs:
    push-python-package-nightly:
        uses: ./.github/workflows/push_python_package.yml
        secrets:
            PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
            PYPI: ${{ secrets.PYPI }}
            TOKEN: ${{ secrets.TOKEN }}


    build-and-push-image-nightly:
        needs: push-python-package-nightly
        uses: ./.github/workflows/build_and_push_image.yml
        with:
            package-base-version: ${{ needs.push-python-package-nightly.outputs.package-base-version }}
            package-dev-version: ${{ needs.push-python-package-nightly.outputs.package-dev-version }}
        secrets:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    create-release-nightly:
        needs: push-python-package-nightly
        uses: ./.github/workflows/create_release.yml
        with:
            package-base-version: "${{ needs.push-python-package-nightly.outputs.package-base-version }}-nightly"
        secrets:
            TOKEN: ${{ secrets.TOKEN }}
