---
name: On PR

on:
  pull_request:
  merge_group:

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:

  push-python-package:
    uses: ./.github/workflows/push_python_package.yml
    secrets:
      PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      PYPI: ${{ secrets.PYPI }}
      TOKEN: ${{ secrets.TOKEN }}

  echo-step:
    runs-on: ubuntu-latest
    needs: push-python-package
    steps:
      - name: Echo
        run: echo ${{ needs.push-python-package.outputs.package-base-version }}

  # build-and-push-image:
  #   needs: push-python-package
  #   uses: ./.github/workflows/build_and_push_image.yml
  #   with:
  #     package-base-version: ${{ needs.push-python-package.outputs.package-base-version }}
  #     package-dev-version: ${{ needs.push-python-package.outputs.package-dev-version }}
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
